language: java
sudo: false
jdk:
- oraclejdk8
before_install:
- chmod +x ./gradlew
script:
- xvfb-run ./gradlew check
- ./gradlew jacocoTestReport
- ./gradlew generateLicenseReport
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew bintrayUpload -Ddeployment=true
    on:
      tags: true
      jdk: oraclejdk8
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: build/reports
    on:
      bracnch: master
      jdk: oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)